# Generated by Django 5.0 on 2023-12-17 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Страна-производитель',
                'verbose_name_plural': 'Страны-производителя',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('date_of_receipt', models.DateTimeField(auto_now_add=True, verbose_name='Дата завоза')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('season', models.CharField(max_length=255, verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.brand', verbose_name='Бренд')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.manufacturercountry', verbose_name='Производитель')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.material', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.product', verbose_name='Инфо о товаре')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапки',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gloves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.brand', verbose_name='Бренд')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.manufacturercountry', verbose_name='Производитель')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.material', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.product', verbose_name='Инфо о товаре')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Перчатки',
                'verbose_name_plural': 'Перчатки',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FurCoat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('removable_part', models.CharField(max_length=255, verbose_name='Съемная часть')),
                ('hood', models.CharField(max_length=255, verbose_name='Капюшон')),
                ('clasp', models.CharField(max_length=255, verbose_name='Застежки')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('shadow', models.CharField(max_length=255, verbose_name='Силуэт')),
                ('collar_style', models.CharField(max_length=255, verbose_name='Стиль воротника')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.brand', verbose_name='Бренд')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.manufacturercountry', verbose_name='Производитель')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.material', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.product', verbose_name='Инфо о товаре')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'FurCoat',
                'verbose_name_plural': 'FurCoats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasp', models.CharField(max_length=255, verbose_name='Застежки')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('width_of_bottom', models.FloatField(verbose_name='Ширина дна')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('belt', models.CharField(max_length=255, verbose_name='Ремень')),
                ('equipment', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('legs', models.CharField(max_length=255, verbose_name='Ножки')),
                ('inside_pockets_count', models.IntegerField(verbose_name='Кол-во внутренних карманов')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.brand', verbose_name='Бренд')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.manufacturercountry', verbose_name='Производитель')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.material', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.product', verbose_name='Инфо о товаре')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Сумка',
                'verbose_name_plural': 'Сумки',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='clothing_store.size', verbose_name='Размеры'),
        ),
    ]
