# Generated by Django 5.0 on 2023-12-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizesproduct',
            name='count',
        ),
        migrations.AddField(
            model_name='size',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товаров данного размера'),
        ),
    ]
