# Generated by Django 5.0 on 2023-12-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0002_remove_sizesproduct_count_size_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество сумок'),
        ),
    ]
