# Generated by Django 5.0 on 2023-12-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0002_alter_furcoat_options_bag_price_furcoat_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='aboba', null=True, upload_to='img/fur_coat/%Y/%m/%d/', verbose_name='Фото сумки')),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.bag', verbose_name='Сумка')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFurCoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='aboba', null=True, upload_to='img/fur_coat/%Y/%m/%d/', verbose_name='Фото шубы')),
                ('fur_coat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.furcoat', verbose_name='Шуба')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGloves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='aboba', null=True, upload_to='img/fur_coat/%Y/%m/%d/', verbose_name='Фото перчатки')),
                ('gloves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.gloves', verbose_name='Перчатки')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='aboba', null=True, upload_to='img/fur_coat/%Y/%m/%d/', verbose_name='Фото шапки')),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_store.hat', verbose_name='Шапка')),
            ],
        ),
    ]
