# Generated by Django 5.0 on 2023-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothing_store', '0002_alter_furcoat_options_bag_price_furcoat_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sell', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('basket', models.ManyToManyField(to='clothing_store.bag', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Продажа сумок',
                'verbose_name_plural': 'Продажи сумок',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FurCoatSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sell', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('basket', models.ManyToManyField(to='clothing_store.furcoat', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Продажа шуб',
                'verbose_name_plural': 'Продажи шуб',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GlovesSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sell', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('basket', models.ManyToManyField(to='clothing_store.gloves', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Продажа перчаток',
                'verbose_name_plural': 'Продажи перчаток',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HatSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sell', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('basket', models.ManyToManyField(to='clothing_store.hat', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Продажа шапок',
                'verbose_name_plural': 'Продажи шапок',
                'managed': True,
            },
        ),
    ]
