# Generated by Django 5.0 on 2023-12-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sold_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagsale',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданных сумок'),
        ),
        migrations.AddField(
            model_name='furcoatsale',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданных шуб'),
        ),
        migrations.AddField(
            model_name='glovessale',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданных перчаток'),
        ),
        migrations.AddField(
            model_name='hatsale',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданных шапок'),
        ),
    ]
